### ISSUE TITLE
A better format for compose key configuration?

### ISSUE THREAD

**Issue by jeanas** [ibus/ibus#2636]
The XCompose configuration file is unfortunately quite horrible:

- The file itself is called "XCompose" as an artifact of Xorg, but the desktop is moving to Wayland. This makes it extremely confusing when searching for information.
- It lives in `~` and not in the correct Freedesktop directory `~/.config`.
- It has substitutions in `include` directives (`%H`, `%L` and `%S`) that don't make sense on systems without Xorg, and which GTK, IBus and other projects interpret differently.
- There are other inconsistencies between projects regarding the supported syntax (things like code points written as `U4040`).
- It's inconvenient to have to look up keysyms when you don't know how they're called (you need to observe `wev` or `xev` output).

For further context, see https://gitlab.gnome.org/GNOME/gtk/-/issues/6630

I'm wondering if you would be open to adding a new convention for the configuration file, in a different, more well-defined format (and read by IBus only). For example, this could be `~/.config/ibus/compose.toml` in [TOML](https://toml.io), which is popular, well-defined and simple enough that parsing it in C can be done without heavy dependencies. The file might look like

```toml
include-default = false

[[sequences]]
input = ["plus", "1"]
output = "👍"

[[sequences]]
input = "|--" # shortcut for ["bar", "minus", "minus"]
output = "\u22A2" # TOML support Unicode escape sequences
```

I'd be willing to do some work on this, but I'd like to hear your opinions first. Thanks!
